package com.kaitait.statemachine;

public enum Events {
    BASKET_PAGE_SEEN,
    BASKET_CREATED,
    BASKET_CREATED_DELIVERY,
    BASKET_CHANGED,

    ADDRESS_PAGE_SEEN,
    ADDRESS_SELECTED,
    ADDRESS_CHANGED,

    TIMESLOT_PAGE_SEEN,
    TIMESLOT_SELECTED,
    TIMESLOT_SELECTED_DELIVERY,
    TIMESLOT_CHANGED,

    PAYMENT_PAGE_SEEN,
    PAYMENT_SELECTED,
    PAYMENT_CHANGED,

    CONFIRMATION_PAGE_SEEN,
    ORDER_CONFIRMED,
    CONFIRMATION_CHANGED,

    AFTER_SALE_SEEN;
}
