package com.kaitait.statemachine;

public enum Events {
    BASKET_PAGE_SEEN,
    BASKET_CREATED,
    BASKET_CHANGED,

    TIMESLOT_PAGE_SEEN,
    TIMESLOT_SELECTED,
    TIMESLOT_CHANGED,

    CONFIRMATION_PAGE_SEEN,
    ORDER_CONFIRMED,
    CONFIRMATION_CHANGED,

    AFTER_SALE_SEEN;

}
